---
openapi: '3.0.2'
info:
  title: lpa-codes-${environment}
  version: '2.0'
servers:
  - url: /v1
    description: we use the path only so we can use in different contexts

paths:
  /healthcheck:
    get:
      summary: "Healthcheck endpoint"
      description: "Checks health of our lambda"
      operationId: api.resources.handle_healthcheck
      security:
        - sigv4: []
      responses:
        200:
          description: OK
  /create:
    post:
      summary: "Create a new code"
      description: "Create a new 12 digit alpha-numeric code unique to this LPA and Actor"
      operationId: api.resources.create_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lpas:
                  type: array
                  items:
                    type: object
                    properties:
                      lpa:
                        type: string
                        pattern: '^([0-9]{12}|([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})|(M(-[0-9A-Z]{4}){3}))$'
                      actor:
                        type: string
                        pattern: '[0-9]{12}|^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
                      dob:
                        type: string
                        format: date
                        pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}$'
              additionalProperties: false
              example:
                lpas:
                  - lpa: "795778824861"
                    actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
                    dob: "1960-06-05"
                  - lpa: "795778824861"
                    actor: "9a619d46-8712-4bfb-a49f-c14914ff319d"
                    dob: "1983-08-20"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeCreated'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
  /validate:
    post:
      summary: "Validate a code"
      description: "Validates the combination of lpa/dob/code is active and valid"
      operationId: api.resources.validate_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lpa:
                  type: string
                dob:
                  type: string
                  format: date
                code:
                  type: string
              example:
                lpa: "795778824861"
                dob: "1960-06-05"
                code: "YsSu4iAztUXm"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateCode'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
  /revoke:
    post:
      summary: "Revoke a code"
      description: "Updates the status of the provided code to revoked"
      operationId: api.resources.revoke_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              example:
                code: "YsSu4iAztUXm"
      responses:
        200:
          description: OK
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
  /mark_used:
    post:
      summary: "Mark a Modernise code as used - set the expiry date from now"
      description: "Mark a Modernise code as used - Updates the expiry_date of the provided code to 2 years from now"
      operationId: api.resources.mark_used_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              example:
                code: "YsSu4iAztUXm"
      responses:
        200:
          description: OK
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
  /exists:
    post:
      summary: "Checks if a code exists for a specific actor on an LPA"
      description: "Checks if a code exists for a specific actor on an LPA"
      operationId: api.resources.actor_code_exists_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lpa:
                  type: string
                actor:
                  type: string
              example:
                lpa: "795778824861"
                actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorCodeExists'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'
  /code:
    post:
      summary: "Returns all details for a code"
      description: "Returns all details for a code"
      operationId: api.resources.actor_code_details_route
      security:
        - sigv4: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              example:
                code: "YsSu4iAztUXm"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodeDetails'
        400:
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error400'
        404:
          description: That URL is not a valid route, or the item resource does not exist
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error404'
        500:
          description: Something unexpected happened and it is the API"s fault
          content:
            application/vnd.opg-data.v1+json:
              schema:
                $ref: '#/components/schemas/Error500'

components:
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      x-apikeyInfoFunc: lpa_codes_mock.apikey_auth #pragma: allowlist secret
  schemas:
    CodeCreated:
      properties:
        codes:
          type: array
          items:
            type: object
            properties:
              lpa:
                type: string
              actor:
                type: string
              code:
                type: string
      example:
        codes:
          - lpa: "795778824861"
            actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
            code: "YsSu4iAztUXm"
          - lpa: "795778824861"
            actor: "9a619d46-8712-4bfb-a49f-c14914ff319d"
            code: "aEYVS6i9zSwy"
      required:
        - codes
    ValidateCode:
      properties:
        actor:
          type: string
      example:
        actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
      required:
        - actor
    ActorCodeExists:
      properties:
        lpa:
          type: string
        actor:
          type: string
      example:
        lpa: "795778824861"
        actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
      required:
        - lpa
        - actor
    CodeDetails:
      properties:
        active:
          type: boolean
        actor:
          type: string
        code:
          type: string
        dob:
          type: string
          format: date
        expiry_date:
          type: string
          format: date
        generated_date:
          type: string
          format: date
        last_updated_date:
          type: string
          format: date
        lpa:
          type: string
        status_details:
          type: string
      example:
        active: true
        code: "YsSu4iAztUXm"
        last_updated_date: 2022-08-20
        status_details: "Generated"
        expiry_date: 2023-08-20
        dob: 1983-08-20
        generated_date: 2022-08-20
        lpa: "795778824861"
        actor: "12ad81a9-f89d-4804-99f5-7c0c8669ac9b"
      required:
        - active
        - actor
        - code
        - dob
        - expiry_date
        - generated_date
        - last_updated_date
        - lpa
        - status_details

    Error400:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-INVALIDREQUEST"
              title:
                type: string
                example: "Invalid Request"
              detail:
                type: string
                example: "Invalid request, the data is incorrect"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error404:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-NOTFOUND"
              title:
                type: string
                example: "Page not found"
              detail:
                type: string
                example: "That URL is not a valid route, or the item resource does not exist"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error500:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: "A123BCD"
              code:
                type: string
                example: "OPGDATA-API-SERVERERROR"
              title:
                type: string
                example: "Internal server error"
              detail:
                type: string
                example: "Something unexpected happened internally"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
